import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import {OptionBarTile} from "option-bar-tile.slint";
import "fonts\nasalization-rg.otf";

export component AppWindow inherits Window {
    title: "F1 APP";
    width: 1920px;
    height: 1080px;
    background: #252525;
    no-frame: false;

    HorizontalLayout {
      
        
        option-bar := VerticalLayout {
            alignment: end;
            width: parent.width * 0.15;
            y: parent.y - 10px;
            outline := 
            Rectangle {
                width: parent.width + 50px;
                x: parent.x - 25px;
                height: parent.height + 20px;
                border-radius: 25px;
                border-width: 10px;
                border-color: white;
                
                logo := Rectangle{ 
                logo-btn:=TouchArea{

                }
                teks:=Text{
                    y: parent.y;
                    x: parent.x + 50px;
                    font-family: "Nasalization";
                    text: "F1.BG";
                    color: white;
                    font-size: 96px;
                    
                    
                }

                spark := Image{
                    source: @image-url("icons/red_lightning.png");
                    y: teks.y + teks.height/3;
                    x: teks.x + 6px;
                    rotation-angle: -30deg;
                    height: 200px;
                    width: 240px;
                    image-rendering: smooth;

                }
            }
            next-race-bet := OptionBarTile{
                y: spark.height + 20px;
                tekst: "Zrób zakład na następny wyścig";
            }

            season-classification := OptionBarTile{
                y:next-race-bet.y + 60px;
                tekst: "Klasyfikacja sezonu";
            }
            ongoing-race := OptionBarTile{
                y: season-classification.y + 60px;
                tekst: "Aktualny wyścig na żywo";
            }

            }
            
       }           
    }
    information-canvas := VerticalLayout {
        x: option-bar.width;
        width: parent.width * 0.85;
        
        

    }
}
    
    


