import {HorizontalBox} from "std-widgets.slint";

export component OptionBarTile{
    in property <string> tekst;
    
    outer := Rectangle{
        height: 50px;
        width: 250px;
        background:  #fffefe ;
        border-radius: 5px;
        
        
    inner := Rectangle {
        height: 45px;
        width: 245px;
        background: tile-btn.has-hover ? #535353 :#252525  ;
        border-radius: 5px;
          }
    inner-text := Text
            {
        color: #FFFFFF;
        text: tekst;
        }   
    tile-btn := TouchArea{
        
    }
     }

}
